#
# Application template.
#
# This defines all the configurable parameters and other objects that are needed to run the jHipster application
# service. This template can even be saved in OpenShift namespace as well so that have the flexibility to do any project specific
# customizations. Pls note wherever displayName says *** PLEASE DO NOT CHANGE THIS ***, don't touch that as those parameters will be
# referenced in other places.
#
apiVersion: v1
kind: Template
metadata:
  name: landingsvc-app-template
  namespace: digital-lending
  annotations:
    description: This template defines objects that are required to spin up an landingsvc service pod
    tags: landingsvc, service
    openshift.io/display-name: landingsvc-template
    openshift.io/long-description: "This template provides objects that are required to spin up a landingsvc service pod."
    openshift.io/provider-display-name: JHipster
labels:
  app: landingsvc-app
  createdBy: JHipster-Team
parameters:
  - name: APPLICATION_NAME
    value: landingsvc
    description: Name of the application
    required: true
    displayName: Application Name
  - name: SECRET_REF
    value: landingsvc-ds-secret-ref
    description: Name of the DataSource Secret Reference
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: EXT_SECRET_REF
    value: ext-landingsvc-ds-secret-ref-ext
    description: Name of the DataSource Secret Reference
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: REG_SECRET_REF
    value: reg-secret-ref
    description: Name of the Registry Secret Reference
    required: true
    displayName: "*** PLEASE DO NOT CHANGE THIS ***"
  - name: APP_PORT
    value: "8203"
    description: Port of the application
    required: true
    displayName: Application Port
  - name: MSSQL_USER
    displayName: MSSQL Connection Username
    description: Username for MSSQL user that will be used for accessing the database.
    value: usr_digilen
    required: true
  - name: MSSQL_PASSWORD
    displayName: MSSQL Connection Password
    description: Password for the MSSQL connection user.
    value: P@ssw0rd
    required: true
  - name: EXT_MSSQL_USER
    displayName: MSSQL Connection Username
    description: Username for MSSQL user that will be used for accessing the database.
    value: usr_digilen
    required: true
  - name: EXT_MSSQL_PASSWORD
    displayName: MSSQL Connection Password
    description: Password for the MSSQL connection user.
    value: P@ssw0rd
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_REF}
    stringData:
      database-user: "${MSSQL_USER}"
      database-password: "${MSSQL_PASSWORD}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${EXT_SECRET_REF}
    stringData:
      database-user: "${EXT_MSSQL_USER}"
      database-password: "${EXT_MSSQL_PASSWORD}"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources:
      replicas: 1
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          imagePullSecrets:
              # - name: bastion-registry # TODO Adjust accordingly
              - name: docker # TODO Adjust accordingly
          containers:
            - name: ${APPLICATION_NAME}
              # image: 172.18.25.125:5000/digital-lending/landingsvc:latest # TODO Adjust accordingly
              # image: 172.18.25.126:5000/digital-lending/landingsvc:latest # TODO Adjust accordingly
              image: docker.io/besmartdevops/landingsvc # TODO Adjust accordingly
              imagePullPolicy: Always
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: prod,api-docs
                - name: SPRING_CLOUD_CONFIG_URI
                  value: http://admin:${jhipster.registry.password}@jhipster-registry:8761/config
                - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
                  value: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
                - name: JHIPSTER_REGISTRY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${REG_SECRET_REF}
                      key: registry-admin-password
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:sqlserver://172.18.28.11:1433;database=DB_UTLITY_DIGILEN # TODO Adjust accordingly
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-user
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${SECRET_REF}
                      key: database-password
                - name: DB_CORE_DATASOURCE_URL
                  value: jdbc:sqlserver://172.18.28.11:1433;database=DB_UTLITY_DIGILEN # TODO Adjust accordingly
                - name: DB_CORE_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${EXT_SECRET_REF}
                      key: database-user
                - name: DB_CORE_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${EXT_SECRET_REF}
                      name: ${SECRET_REF}
                      key: database-password
                - name: SPRING_ELASTICSEARCH_REST_URIS
                  value: http://${APPLICATION_NAME}-elasticsearch:9200
                - name: SPRING_LIQUIBASE_URL
                  value: jdbc:sqlserver://172.18.28.11:1433;database=DB_UTLITY_DIGILEN
                - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
                  value: http://172.18.28.10:9080/auth/realms/jhipster # TODO Adjust accordingly
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
                  value: web_app
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
                  value: web_app
                - name: SPRING_ARTEMIS_USER
                  value: admin
                - name: SPRING_ARTEMIS_PASSWORD
                  value: admin
                - name: SPRING_ARTEMIS_HOST
                  value: artemis # TODO Adjust accordingy
                - name: SPRING_ARTEMIS_PORT
                  value: "61616"
                - name: SPRING_JPA_DATABASE_PLATFORM
                  value: org.hibernate.dialect.SQLServer2012Dialect
                - name: SPRING_JPA_PROPERTIES_HIBERNATE_DDL_AUTO
                  value: update
                - name: SPRING_JPA_SHOW_SQL
                  value: "false"
                - name: SPRING_JPA_GENERATE_DDL
                  value: "true"
                - name: FTP_SERVER
                  value: vm1.atiila.id
                - name: FTP_PORT
                  value: "21"
                - name: FTP_USERNAME
                  value: testuser
                - name: FTP_PASSWORD
                  value: nop4ssword@2021
                - name: DISBURSEMENT_FTPSOURCE_SERVER
                  value: vm1.atiila.id
                - name: DISBURSEMENT_FTPSOURCE_PORT
                  value: "21"
                - name: DISBURSEMENT_FTPSOURCE_USERNAME
                  value: testuser
                - name: DISBURSEMENT_FTPSOURCE_PASSWORD
                  value: nop4ssword@2021
                - name: DISBURSEMENT_FTPSOURCE_PATH
                  value: /tmp/demo/dirc
                - name: DISBURSEMENT_FTPSOURCE_PATHBACKUP
                  value: /tmp/demo/backup
                - name: DISBURSEMENT_FTPSOURCE_LISTFILES
                  value:
                - name: DISBURSEMENT_FTPDESTINATION_SERVER
                  value: localhost
                - name: DISBURSEMENT_FTPDESTINATION_PORT
                  value: "21"
                - name: DISBURSEMENT_FTPDESTINATION_USERNAME
                  value: one
                - name: DISBURSEMENT_FTPDESTINATION_PASSWORD
                  value: "1234"
                - name: DISBURSEMENT_FTPDESTINATION_PATH
                  value: /upload
              ports:
                - name: http
                  containerPort: ${{APP_PORT}}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      selector:
        app: ${APPLICATION_NAME}
      type: LoadBalancer
      ports:
        - name: http
          port: ${{APP_PORT}}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}
    spec:
      to:
        kind: Service
        name: ${APPLICATION_NAME}
        weight: 100
      port:
        targetPort: "http"
      wildcardPolicy: None
