# Search template.
#
# This defines all the configurable parameters and other objects that are needed to run the Elasticsearch service. This template can even
# be saved in OpenShift namespace as well so that have the flexibility to do any project specific customizations. Pls note wherever
# displayName says *** PLEASE DO NOT CHANGE THIS ***, don't touch that as those parameters will be referenced in other places.
#
apiVersion: v1
kind: Template
metadata:
  name: landingsvc-elasticsearch-template
  namespace: digital-lending
  annotations:
    description: This template defines objects that are required to spin up an elasticsearch pod
    tags: elasticsearch, landingsvc-elasticsearch  ,ephemeral
    openshift.io/display-name: landingsvc-elasticsearch-template
    openshift.io/long-description: >-
      This template provides objects that are required to spin up an elasticsearch pod.
      The database is not stored on persistent storage, so any restart of the service will result in all data being lost.
    openshift.io/provider-display-name: JHipster-OpenShift
labels:
  app: landingsvc-elasticsearch
  createdBy: JHipster-Team
parameters:
  - name: APPLICATION_NAME
    value: landingsvc-elasticsearch
    description: Name of the application
    required: true
    displayName: Application Name
  - name: VOLUME_CAPACITY
    displayName: Volume Capacity
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    value: 1Gi
    required: true
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      # This is to define the deployment strategy (either be Rolling or Recreate)
      #     strategy:
      #       type: Rolling
      #       rollingParams:
      #         updatePeriodSeconds: 1
      #         intervalSeconds: 1
      #         timeoutSeconds: 600
      #         maxUnavailable: 25%
      #         maxSurge: 25%
      #       resources:
      triggers:
        - type: ConfigChange
      replicas: 1
      selector:
        app: ${APPLICATION_NAME}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
        spec:
          volumes:
            - name: ${APPLICATION_NAME}-data
              emptyDir: {}
          containers:
            - name: ${APPLICATION_NAME}
              image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
              ports:
                - containerPort: 9200
                  name: http
                  protocol: TCP
                - containerPort: 9300
                  name: transport
                  protocol: TCP
              volumeMounts:
                - name: ${APPLICATION_NAME}-data
                  mountPath: /usr/share/elasticsearch/data/
              resources:
              imagePullPolicy: IfNotPresent
              env:
                - name: discovery.type
                  value: single-node
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: http
          port: 9200
          protocol: TCP
          targetPort: 9200
        - name: transport
          port: 9300
          protocol: TCP
          targetPort: 9300
      selector:
        app: ${APPLICATION_NAME}
