apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: artemis
  name: artemis
spec:
  ports:
    - name: "5445"
      port: 5445
      targetPort: 5445
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "8161"
      port: 8161
      targetPort: 8161
    - name: "61616"
      port: 61616
      targetPort: 61616
    - name: "61613"
      port: 61613
      targetPort: 61613
    - name: "61614"
      port: 61614
      targetPort: 61614
  selector:
    io.kompose.service: artemis
status:
  loadBalancer: {}
